### ISSUE TITLE
Problems with this guide

### ISSUE THREAD

**Issue by RocketLauncher21** [P0L3NARUBA/gtav-sourcecode-build-guide#1]
There are quite a few problems with your guide:
1. It is based off this [rentry.co](https://rentry.co/bettergtavbuildguide) guide, not the one you have in there
2. You link to a lot of unneccesary files / SDKs that won't mostly help
3. Providing DLL patches and the actual source code is VERY likely to get taken down by Rockstar. You should probably change that...

**Comment by WH0LEWHALE** [comment]
That files are actually optional so you can ignore them.
Okay i will do something about it, maybe converting all the rush patches, dll patches and the source code links to base64?

**Comment by WH0LEWHALE** [comment]
That files are actually optional so you can ignore them.
I will use another way to share the DLL, Rush and Source Code links..
