### ISSUE TITLE
Epic Games Not Working

### ISSUE THREAD

**Issue by gta-guy** [P0L3NARUBA/gtav-sourcecode-build-guide#10]
**Informational:**
First I tried with Epic Games version of the game, I can't make it work.
Then I tried with Steam version, it worked without any problem.
(Both versions are original, not torrent)

**Comment by AnomaliesGentoolman** [comment]
I have Epic Games version and it works fine.

**Comment by gta-guy** [comment]
I don't know I just made same steps as steam version, epic didn't work.

**Comment by AnomaliesGentoolman** [comment]
What error it gives?
