### ISSUE TITLE
ragScriptEditor - Loading Projects stuck at zero

### ISSUE THREAD

**Issue by kaanalsoy43** [P0L3NARUBA/gtav-sourcecode-build-guide#15]
I recently build the whole game and played with it, and then i decided to compile scripts because i dont want prebuilt shit.....
But this happened:
![bruh](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/161887411/e633f520-8f0c-4f34-82fc-8057fb81ac07)

Its been like that for 2 and a half hours but still stays at zero*

**Comment by AnomaliesGentoolman** [comment]
Just try in Virtual Machine and set VM CPU Core to Single Core(1).

**Comment by kaanalsoy43** [comment]
I Have Virtualbox, is that will work?

**Comment by kaanalsoy43** [comment]
And my SSD never feel happy about this because already 300GB Full, i will allocate 100GB to vm and try making the whole game in that virtual machine... That will take a whole day for me.

**Comment by AnomaliesGentoolman** [comment]
@kaanalsoy43 Yeah Virtualbox will probably work

**Comment by kaanalsoy43** [comment]
Okay it actually worked thanks for the help!
