### ISSUE TITLE
Shaders building ends with errors

### ISSUE THREAD

**Issue by Sotlef** [P0L3NARUBA/gtav-sourcecode-build-guide#18]
I already successfully built application but cannot build shaders..

I launched VS2012 via **X:\gta5\src\dev_ng\game\VS_Project\load_sln_unity_2012.bat**
SETTING SPECIFIC ENVIRONMENT VALUES TO OVERRIDE SETENV.BAT
OVERRIDES:
RS_BUILDBRANCH:    x:\gta5\build\dev_ng
RS_CODEBRANCH:     x:\gta5\src\dev_ng
RS_PROJECT:        gta5
RS_PROJROOT:       x:\gta5
RS_SCRIPTBRANCH:   x:\gta5\script\dev_ng
RS_TOOLSROOT:      X:\gta5\tools_ng
RAGE_DIR:          X:\gta5\src\dev_ng\rage
RS_TITLE_UPDATE_NG:          x:\gta5\titleupdate\dev_ng
ENVIRONMENT
RS_PROJECT:         gta5
RS_PROJROOT:        x:\gta5
RS_BUILDROOT:       x:\gta5\build
RS_BUILDBRANCH:     x:\gta5\build\dev_ng
RS_CODEBRANCH:      x:\gta5\src\dev_ng
RS_SCRIPTBRANCH:    x:\gta5\script\dev_ng
RS_ASSETS:          x:\gta5\assets_ng
RS_EXPORT:          x:\gta5\assets_ng\export
RS_PROCESSED:       x:\gta5\assets_ng\processed
RS_TOOLSROOT:       X:\gta5\tools_ng
RS_TOOLSBIN:        X:\gta5\tools_ng\bin
RS_TOOLSDCC:        X:\gta5\tools_ng\dcc
RS_TOOLSCONFIG:     X:\gta5\tools_ng\etc
RS_TOOLSLIB:        X:\gta5\tools_ng\lib
RS_TOOLSSRC:        x:\gta5\src\dev_ng\rage\framework\tools\src
RS_TOOLSRUBY:       X:\gta5\tools_ng\bin\ruby\bin\ruby.exe
RS_TOOLSIR:         X:\gta5\tools_ng\bin\ironruby\bin\ir64.exe
RS_TOOLSPYTHON:     X:\gta5\tools_ng\bin\python\App\python.exe
RS_TOOLSCONVERT:    X:\gta5\tools_ng\ironlib\lib\RSG.Pipeline.Convert.exe
**RAGE_DIR:           X:\gta5\src\dev_ng\rage**
RAGE_3RDPARTY:      X:\3rdparty\dev
RAGE_CRASHDUMP_DIR: x:\gta5\build\dev_ng
RS_TITLE_UPDATE:    x:\gta5\titleupdate\dev
END ENVIRONMENT

I get errors:
1>------ Build started: Project: shaders_rc, Configuration: Release Win32 4.0 Win32 ------
1>  Setting platform to: win32_40
1>EXEC : error : Cannot find shader dependency file: **%RAGE_DIR%**/base/src/shaderlib/rage_common.fxh
1>EXEC : error : Cannot find shader dependency file: **%RAGE_DIR%**/base/src/grcore/config_switches.h
1>EXEC : error : Cannot find shader dependency file: **%RAGE_DIR%**/base/src/grcore/config_switches.h
1>EXEC : error : Cannot find shader dependency file: **%RAGE_DIR%**/base/src/shaderlib/rage_diffuse_sampler.fxh
...
1>EXEC : error : Cannot find shader dependency file: **%RAGE_DIR%**/base/src/grcore/config_switches.h
1>  Building Incredibuild XML File: C:\Users\sotlef\AppData\Local\Temp\XGEShaderBuild.xml
1>  Please Wait...
1>  
1>  Shader Build: win32_40
1>  
1>  
1>  -----------------------------------------------------------------
1>  Xoreax Grid Engine Console 4.0 (build 1281)
1>  Copyright (C) 2001-2012 Xoreax Software Ltd. All rights reserved.
1>  -----------------------------------------------------------------
1>  
1>  
1>  Initializing...
1>  --------------------Project: FX Shader Compiling-------------------------------
1>  Compiling Shaders
1>  |   X:\gta5\tools_ng\bin\RageShaderManager\RAGEShaderManager.exe  -shader=X:\gta5\src\dev_ng\game\shader_source\Custom\blend_2lyr.fx -config=X:\gta5\tools_ng\etc\RageShaderManager\shaderbuild_tu_dev_ng.xml -action cleanbuild -noDependencies  -platform win32_40 -platformConfig final
1>  Compiling blend_2lyr.fx (0:00.21 at +0:00)
1>  Setting platform to: win32_40
1>  Setting platform config: final
1>  Building: X:\gta5\src\dev_ng\game\shader_source\Custom\blend_2lyr.fx
**1>EXEC : error : %RAGE_DIR% -> Could not resolve this variable. Please check your configuration file.
1>EXEC : error : Error in preprocessor on shader: X:\gta5\src\dev_ng\game\shader_source\Custom\blend_2lyr.fx**
1>  Exit Code: 1
1>EXEC : error : Shader Build Failed

**Comment by AnomaliesGentoolman** [comment]
Are you using incredibuild to build the shaders?

**Comment by Sotlef** [comment]
Yep (I think so)
I installed it and have such lines in output:
1> Building **Incredibuild** XML File: C:\Users\sotlef\AppData\Local\Temp\XGEShaderBuild.xml
1> Please Wait...

**Comment by Sotlef** [comment]
I added RAGE_DIR to user environment variables and restart Visual Studio, the errors are gone

**Comment by AnomaliesGentoolman** [comment]
good

**Comment by Sotlef** [comment]
ok, shaders was successfully compiled
