### ISSUE TITLE
An error message appeared after opened up exe?

### ISSUE THREAD

**Issue by opusbullet5050** [P0L3NARUBA/gtav-sourcecode-build-guide#24]
Screenshot:
![image](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/162581825/b815b47a-c5c1-4aa7-a692-b6d497eb9f33)

The Program closed itself; this is a virus or no?

**Comment by AnomaliesGentoolman** [comment]
9/11 incident

**Comment by reactEASYEZ** [comment]
or no

**Comment by AnomaliesGentoolman** [comment]
why did you open issue for this??? you are using a f*cking .bat file to generate this error message box....
