### ISSUE TITLE
incredibuild4_0

### ISSUE THREAD

**Issue by leaningmonkevr** [P0L3NARUBA/gtav-sourcecode-build-guide#27]
i cant open the app cus its saying its a virus but its not so i cant open it

 -note i have virus and threat protection off

**Comment by AnomaliesGentoolman** [comment]
1. Hold Shift and right click the `incredibuild4_0.exe` file, select "Copy as path"
   2. Open Command Prompt as Administrator
   3. Paste the path and press Enter
   - Select to install "Incredibuild Agent", "Incredibuild Coordinator", and the extension for Visual Studio.

**Comment by leaningmonkevr** [comment]
Thank you
