### ISSUE TITLE
X drive

### ISSUE THREAD

**Issue by leaningmonkevr** [P0L3NARUBA/gtav-sourcecode-build-guide#28]
![image_2024-04-18_160211858](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/132413522/3ea7c3f4-14a9-4cef-8ea9-a84c8e3f89fa)

sould i open command prompt as admin?

**Comment by AnomaliesGentoolman** [comment]
No you entered path wrong

**Comment by AnomaliesGentoolman** [comment]
It should be net use X: \\localhost\c$\Users\Owner\Desktop\GTA /persistent:yes

**Comment by AnomaliesGentoolman** [comment]
If this fixed your problem, you can close this issue as completed.

**Comment by leaningmonkevr** [comment]
it worked
