### ISSUE TITLE
i dont know what the title sould be

### ISSUE THREAD

**Issue by leaningmonkevr** [P0L3NARUBA/gtav-sourcecode-build-guide#31]
i cant find Active Solution Platform in the configuration window

**Comment by AnomaliesGentoolman** [comment]
try clicking configuration on the left side, then you should see them.

**Comment by AnomaliesGentoolman** [comment]
are you on this step?

**Comment by leaningmonkevr** [comment]
Change "Active Solution Platform" to "x64" and close the configuration window its this one

**Comment by AnomaliesGentoolman** [comment]
can you screenshot the window?

**Comment by leaningmonkevr** [comment]
![Screenshot 2024-04-18 181607](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/132413522/baf17d85-7052-4f06-beda-03f494545d9a)
 
![Screenshot 2024-04-18 181644](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/132413522/93fa3a5c-e0be-4fa1-8373-645f80471211)

**Comment by AnomaliesGentoolman** [comment]
Here, at the top it says Durango, change that to x64 and change the Final to BankRelease!!!!!

**Comment by leaningmonkevr** [comment]
Hold Ctrl key and click all projects under "GameLibs" and "Rage", right-click and select "Properties" what do you mean on this step?

**Comment by AnomaliesGentoolman** [comment]
do you see gamelibs and rage folders on the right side, yeah just hold ctrl key and select the contents of the gamelibs folder and enter properties, apply the thing and do the same thing to the rage folder too.

**Comment by AnomaliesGentoolman** [comment]
I should make a video about it fr

**Comment by leaningmonkevr** [comment]
yeah it will help a lot to someone who wants to have fun playing gta 5 source code

**Comment by AnomaliesGentoolman** [comment]
you saying right, i should make a video and cover everything.

**Comment by AnomaliesGentoolman** [comment]
I will do it when i have free time

**Comment by leaningmonkevr** [comment]
what is a output binary?

**Comment by AnomaliesGentoolman** [comment]
the executable after compiling.

**Comment by leaningmonkevr** [comment]
k

**Comment by leaningmonkevr** [comment]
On Patching Game Assets step 2 where is the game folder?

**Comment by leaningmonkevr** [comment]
![image_2024-04-18_200718993](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/132413522/43fd4592-f5d3-40c5-875c-698a256d121d)

what is missing?

**Comment by AnomaliesGentoolman** [comment]
put that executable to your gta v game directory.
