### ISSUE TITLE
game project doesn’t wanna compile

### ISSUE THREAD

**Issue by Pcniado** [P0L3NARUBA/gtav-sourcecode-build-guide#32]
[message.txt](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/files/15048549/message.txt)

**Comment by Pcniado** [comment]
what do i do

**Comment by yungDoom** [comment]
It says unresolved external symbol, there is 3 ways to probably make it work
Rebuild
Start everything from scratch
Try making the whole game in virtual machine.

**Comment by Pcniado** [comment]
what does doing it in a vm change

**Comment by yungDoom** [comment]
Nothing but in a vm it will %100 work, in real machine sometimes the conflicts may happen. In Virtual Machine there will be no conflict.

**Comment by Pcniado** [comment]
i guess i can try selecting all the solutions and clicking rebuild

**Comment by yungDoom** [comment]
Yeah maybe

**Comment by Pcniado** [comment]
![IMG_9561](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/122915996/5264404b-df3a-4c0a-8158-803e4d47b3ff)
sadly it failed so i’ll try vm later

**Comment by Pcniado** [comment]
i tried r

**Comment by JuniorBros** [comment]
Try to build it in debug, not bankrelease

**Comment by yungDoom** [comment]
> Try to build it in debug, not bankrelease

that will cost a lot of performance
