### ISSUE TITLE
Have everything compiled, all files are in place, I'm receiving this error.

### ISSUE THREAD

**Issue by cspencer49519** [P0L3NARUBA/gtav-sourcecode-build-guide#33]
I have everything in the right places AFAIK, but I receive this error after the initial intro to the game:

![error1](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/13656264/5ea43f53-bf90-45ac-bc7c-16f71247f816)

Any ideas?

**Comment by yungDoom** [comment]
Put the game scripts.

**Comment by cspencer49519** [comment]
> Put the game scripts.



> Put the game scripts.

Where do I put the scripts? I've replaced update and update2 in the update directory, do I need to add the scripts manually with OpenIV?

**Comment by yungDoom** [comment]
Yeah you need to put scripts manually

**Comment by cspencer49519** [comment]
> Yeah you need to put scripts manually

OK, let me give that a try, thanks.

> Yeah you need to put scripts manually

Thank you! Got it working.
