### ISSUE TITLE
Rag cant detect game

### ISSUE THREAD

**Issue by DanielLMcGuire** [P0L3NARUBA/gtav-sourcecode-build-guide#37]
I opened rag (with cmd and using setenv)

The game will not connect to rag, it just launched without it.

Edit: game_win64_bankrelease.exe refuses to run from a bat file or from cmd

**Comment by yungDoom** [comment]
can you just add `-rag -ragUseOwnWindow`
dont forget to launch rag again before launching game :)

**Comment by DanielLMcGuire** [comment]
@yungDoom Yes, it launches from .bat now, rag is launched, but it just acts as a normal game and rag sees no connections

**Comment by yungDoom** [comment]
did you added the parameters to the launch.bat?

**Comment by DanielLMcGuire** [comment]
Yes

**Comment by yungDoom** [comment]
did you blocked rag in firewall?

**Comment by DanielLMcGuire** [comment]
No

**Comment by yungDoom** [comment]
thats weird...

**Comment by DanielLMcGuire** [comment]
I'm going to recompile it so hopefully something will happen

**Comment by yungDoom** [comment]
okay but before recompiling it, can you try put these commands to launch.bat in your game directory and try again?

```
cd %~dp0
game_win64_bankrelease.exe -noSocialClub -nokeyboardhook -nonetlogs -rag -ragUseOwnWindow -DoReleaseStartup
```

**Comment by DanielLMcGuire** [comment]
Still doing the same thing

**Comment by yungDoom** [comment]
do you launched rag before launching the game?

**Comment by DanielLMcGuire** [comment]
Yes

**Comment by DanielLMcGuire** [comment]
Just to be sure, is there anything i need to do to the game files (steam) before launching or anything?

**Comment by yungDoom** [comment]
no

**Comment by DanielLMcGuire** [comment]
Just went into Task Manager, and even though the bat launched game_win64_bankrelease.exe task manager said that the running file was the stock GTAV.exe

**Comment by yungDoom** [comment]
hmm so thats why the launch parameters doesnt work

**Comment by yungDoom** [comment]
Maybe some files missing from your game files??

**Comment by DanielLMcGuire** [comment]
Fixed the problem by compiling on my pc instead of a VM, Now it says game ownership is taking longer than usual (I am on the steam copy so I do own the game)

**Comment by yungDoom** [comment]
send a screenshot

**Comment by DanielLMcGuire** [comment]
![Screenshot (3)](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/146508360/ce61d562-123b-48e5-84dd-6434bcaf3c9f)

**Comment by DanielLMcGuire** [comment]
Also if i change the GTA5.exe in the launch bat file to PlayGTAV.exe, rag launches and connects but the game crashes at this screen

**Comment by yungDoom** [comment]
so weird, i dont get this error...

**Comment by DanielLMcGuire** [comment]
The gta 5 session that i said crashed earlier is just running in the background somehow

**Comment by DanielLMcGuire** [comment]
I got past by setting the launch bat back to playGTA5.exe

**Comment by yungDoom** [comment]
its normal

**Comment by DanielLMcGuire** [comment]
Do i just wait?

**Comment by DanielLMcGuire** [comment]
So after around 10 - 20 minutes after launching with the rag arguments, either rag or the game decides to crash (usually the game)

**Comment by yungDoom** [comment]
> So after around 10 - 20 minutes after launching with the rag arguments, either rag or the game decides to crash (usually the game)

This is not right, there is maybe a problem about update.rpf files? try to use the new ones that i've posted: https://mega.nz/file/72plXYpY#B9A3vDidqPUVhfXDP5hWCS8lc90lcdGZsGfjuWkBDe8

Please tell me if this worked.
