### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by g0dzcsgo** [P0L3NARUBA/gtav-sourcecode-build-guide#43]
I built it successfuly, and ran it fine. Until I tried to change the graphics settings and then restarted. Now whenever I start the game I get an error saying:

Fatal Error: <RenderThread> Unable to create default effect 'common:/shaders/im', cannot continue.

How can I fix it?

Do I need to re-install the src, and redo all the steps?

**Comment by yungDoom** [comment]
No you dont have low quality shaders so thats why its crashing, i will post the fix here wait a sec

**Comment by yungDoom** [comment]
If this method worked, please close this issue.
