### ISSUE TITLE
Can't symlink

### ISSUE THREAD

**Issue by Holo-Y** [P0L3NARUBA/gtav-sourcecode-build-guide#44]
If i try to symlink the directory "X:\gta5\titleupdate\dev_ng" i get this error: "Local NTFS volumes are required to complete this operation." (translated so maybe it's not the exact error, but it's basically that)

**Comment by yungDoom** [comment]
where is your game located at?

**Comment by Holo-Y** [comment]
"C:\Program Files\Epic Games\GTAV"

**Comment by yungDoom** [comment]
mklink /D /J "X:\gta5\titleupdate\dev_ng" "C:\Program Files\Epic Games\GTAV"

can you try this?

**Comment by Holo-Y** [comment]
same

**Comment by yungDoom** [comment]
then just cut and paste the game files to the X:\gta5\titleupdate\dev_ng

**Comment by yungDoom** [comment]
or X:\gta5\build\dev_ng

**Comment by Holo-Y** [comment]
i don't have that directory
![Screenshot 2024-04-26 213714](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/123390620/1fbf0677-ba68-4e8d-b08b-7c5185f683f6)

**Comment by yungDoom** [comment]
you can create.

**Comment by Holo-Y** [comment]
just to clarify, do i need to drag the files inside GTAV or the folder itself?

**Comment by yungDoom** [comment]
yeah drag the files inside of GTAV folder.

**Comment by Holo-Y** [comment]
ok thanks dude
