### ISSUE TITLE
Can't load project on the Script Editor (it crashes when loading)

### ISSUE THREAD

**Issue by Holo-Y** [P0L3NARUBA/gtav-sourcecode-build-guide#46]
Basically when i try to open GTA5_SP.scproj, it crashes while building cache at exactly 1221/3993

**Comment by yungDoom** [comment]
If you're on vm try making the vm single core and try it again. I was have the same problem too, i compiled all the scripts in vm without any problem.

**Comment by yungDoom** [comment]
And dont forget to put dll patches if you dont.

**Comment by Holo-Y** [comment]
I've already tried single core, dual core, quad core and repeated the steps like 3 times on 3 different os (ltsc, windows 11, and now 10). Btw when i tried single core it was stuck at 0 for like an hour

**Comment by Holo-Y** [comment]
I'm reinstalling ltsc and redoing all the steps once again because i have no clue, i'll be back in 1-2 hours to see if tell you if i fixed it for some reason

**Comment by yungDoom** [comment]
🆗

**Comment by Holo-Y** [comment]
Ok, for some reason it now works and it loaded without any problem in a couple of minutes (quad-core). I don't really know what changed from last time (except that i used ltsc but i that doesn't actually mean anything), but now i can build the project. So apparently the solution is to redo every step in a fresh build on a vm, the only reason is that i did something wrong, i don't really know tho. Btw, what name should i give to the file i have to build?

**Comment by yungDoom** [comment]
You don't need to rename anything, when building done the script.rpf file will magically appear in 'X:\gta5\titleupdate\dev_ng\x64\levels\gta5\script\' @Holo-Y

**Comment by Holo-Y** [comment]
Oh ok i was asking just beacuse he asked me to choose a name, i left "new file 1". Btw, it's taking so long, is it normal? How much time should it take?

**Comment by yungDoom** [comment]
> Oh ok i was asking just beacuse it asked me to choose a name, i left "new file 1". Btw, it's taking so long, is it normal? How much time should it take?

XDD it should take more than 2 hours depending cpu, for me i used sungle cored and it took 12+ hours 💀

**Comment by yungDoom** [comment]
Oh and btw, i think you should close this issue as your probelm fixed...
