### ISSUE TITLE
Network Fix

### ISSUE THREAD

**Issue by GTA-Source-Helper** [P0L3NARUBA/gtav-sourcecode-build-guide#51]
I found a fix for the source code called the Network Fix i dont really know what it does but it has a little discription maybe it would be a nice addon for this guide if you need a copy of it DM me on discord: Franklin_Clinton 
Here are some screenshots:
![image](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/168548481/a8220e40-6fc8-42c2-a61f-2ab4f336a416)
![image](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/168548481/5e1d98d2-ff53-47c2-9cd8-dad7656c59ad)
Have a good day

**Comment by yungDoom** [comment]
Thanks man, if someone needs it they can use it.
