### ISSUE TITLE
Some Tools' Network Issue

### ISSUE THREAD

**Issue by gta-guy** [P0L3NARUBA/gtav-sourcecode-build-guide#52]
Some tools like MoVE require login, I wish there was a bypass for this.
![Capture](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/166761095/3a56d6a9-a557-417a-8361-a7053fbfc851)

**Comment by yungDoom** [comment]
Its easy to bypass but i dont know how to do it

**Comment by gta-guy** [comment]
@yungDoom why is this issue closed? 
Maybe someone else can help.

**Comment by yungDoom** [comment]
yeah lets see.

**Comment by yungDoom** [comment]
Can you try [this](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/issues/51)

**Comment by yungDoom** [comment]
And Also, it works for me:
![image](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/146978592/028f8ab3-22ea-4df8-9a19-b10c5ab18f6a)

**Comment by gta-guy** [comment]
@yungDoom now click File->New

**Comment by yungDoom** [comment]
oh...

**Comment by yungDoom** [comment]
I already mentioned about these in my guide:
- [x] Other Tools
    - Note that Some Perforce login required tools will not work, they need some modifications and Perforce.
      - Perforce Download Links:
        1. Helix Core: https://www.perforce.com/downloads/helix-core-free-small-teams
        2. Helix Visual Client: https://www.perforce.com/downloads/helix-visual-client-p4v

The Solution is, you need to compile the program yourself and modify some code in order to make it work...
