### ISSUE TITLE
In the editor, select File > Open Project and open X:\gta5\script\dev_ng\singleplayer\GTA5_SP.scproj The Editor close 

### ISSUE THREAD

**Issue by emanueldev1** [P0L3NARUBA/gtav-sourcecode-build-guide#55]
![image](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/90418449/604f8ab5-dace-4a66-8943-468ad45207b3)
here crash

**Comment by yungDoom** [comment]
Sorry to hear that, for me it works, you should try everything again in a fresh vm. Thats all can you do at this point...
