### ISSUE TITLE
Story Mode will not Load 

### ISSUE THREAD

**Issue by JuniorBros** [P0L3NARUBA/gtav-sourcecode-build-guide#56]
Hi, I had manage to compile the game and make it launch, but the problem is that storymode is not loading, rag is crashing, should i use the goldburg patch for steam?

**Comment by yungDoom** [comment]
can you send a screenshot?

**Comment by JuniorBros** [comment]
![Screenshot 2024-05-04 124346](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/166945518/3d7b62ba-71a7-4c8a-ba0d-367d01e21334)

When i try to launch it in rag, it opens the game but wont make it to the loading screen

**Comment by yungDoom** [comment]
I don't know how to fix it but lets hope that someone help you.

**Comment by JuniorBros** [comment]
im going to do this with the rockstar games launcher, hope it works

**Comment by yungDoom** [comment]
okay

**Comment by JuniorBros** [comment]
Can the build be use in a different version because the version 2699 has problems with infinite loading screens

**Comment by yungDoom** [comment]
Try these update.rpf files, you know where to put:
https://mega.nz/file/72plXYpY#B9A3vDidqPUVhfXDP5hWCS8lc90lcdGZsGfjuWkBDe8

**Comment by JuniorBros** [comment]
did not work, but i think the problem is the gameconfig file in update.rpf

**Comment by yungDoom** [comment]
hmm idk

**Comment by JuniorBros** [comment]
gonna try in VM now

**Comment by JuniorBros** [comment]
Kinda got the Loading screen unstuck, but didn't got into the game yet, but what specs for the VM to run GTAV

**Comment by yungDoom** [comment]
bro dont launch the game in vm, just get the binary to your real pc and play the game here

**Comment by yungDoom** [comment]
As we talked on discord and you said now its working, so i will close this issue.

**Comment by JuniorBros** [comment]
If Anyone is having this problem, most likely your executable is bad, make sure to redo it in a Virtual machine
