### ISSUE TITLE
3rdparty.7z Down

### ISSUE THREAD

**Issue by user6972** [P0L3NARUBA/gtav-sourcecode-build-guide#6]
https://cdn.discordapp.com/attachments/1191001559794995220/1218742498948550666/3rdParty.7z?ex=6611ffe6&is=65ff8ae6&hm=0324e5011bcd288924df7e1edeada857a7ca201029c08ded7acd1ab418e941a3&

"This content is no longer available"

**Comment by AnomaliesGentoolman** [comment]
Thanks for noticing me, i will update it.

**Comment by AnomaliesGentoolman** [comment]
Okay i'll update it soon.

**Comment by AnomaliesGentoolman** [comment]
I'm uploading the file to the Mega.nz right now.

**Comment by AnomaliesGentoolman** [comment]
Now its up!
