### ISSUE TITLE
More Info About Prebuilt Files

### ISSUE THREAD

**Issue by gta-guy** [P0L3NARUBA/gtav-sourcecode-build-guide#8]
I think you have to add more info about Prebuilt Files(Shaders & Scripts).
Example where should we move to shaders?
Game folder or X:\gta5\titleupdate\dev_ng\common?
Same for scripts etc.

Thank you for this repo.

**Comment by AnomaliesGentoolman** [comment]
Yeah, you should move shaders to the game directory, for the script you need edit update2.rpf from openIV

**Comment by gta-guy** [comment]
Can you make step 8 a little clearer? 
I think we will use the C:\Desktop\GTA folder as a virtual x drive. 
What should I do if I already have x drive?

**Comment by AnomaliesGentoolman** [comment]
use the x drive if you already have x drive.
