### ISSUE TITLE
Can't Open Rag

### ISSUE THREAD

**Issue by gta-guy** [P0L3NARUBA/gtav-sourcecode-build-guide#9]
I was able to enter the game without any problems, but I cannot open rag.
![Desktop Screenshot 2024 04 12 - 11 04 00 13](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/166761095/f7353ef7-fc07-4379-8bc6-84a1fc5b46b0)

**Comment by AnomaliesGentoolman** [comment]
hmm thats really weird.
Can you try launching the game first and then rag.
And what graphics card did you have?

**Comment by AnomaliesGentoolman** [comment]
This is very weird, why rag doesnt open while the game itself works perfect..

**Comment by gta-guy** [comment]
If I open game first then open rag:
![img](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/166761095/90bc52db-7499-42c6-9b08-664faa0624ea)

**Comment by AnomaliesGentoolman** [comment]
did you launched with launch.bat?

**Comment by gta-guy** [comment]
In first picture yes I launched with launch.bat but not in second picture.

**Comment by AnomaliesGentoolman** [comment]
can you try adding `-ragUseOwnWindow` to the launch.bat

**Comment by gta-guy** [comment]
Now it is working without any problem, thank you. Arg worked.

**Comment by AnomaliesGentoolman** [comment]
Good, Skidstar probably broke something.

**Comment by AnomaliesGentoolman** [comment]
![image](https://github.com/P0L3NARUBA/gtav-sourcecode-build-guide/assets/146978592/e5151322-2e94-4bcb-aec9-d121ba57a2f3)

It works for me...

**Comment by gta-guy** [comment]
This issue was resolved by running **launch.bat** with "Run as administrator".
